### ISSUE TITLE
build has been failing for the past 6 months

### ISSUE THREAD

**Issue by ogu2** [plivo/plivo-python#117]
According to https://travis-ci.org/plivo/plivo-python/builds it looks like builds have been failing for the past 6months. Looks like it's caused by API server access errors.

Should this be a concern? Also, plans to fix this? I'm evaluating plivo and this might be a blocker.

Thanks

**Comment by huzaif-plivo** [comment]
@ogu2 This has been addressed in our most recent release([v4.18.1](https://github.com/plivo/plivo-python/releases/tag/v4.18.1)), and the status of our UTs can now be found on [Github Actions](https://github.com/plivo/plivo-python/actions).
