### ISSUE TITLE
Call drops immediately; cannot hear the message

### ISSUE THREAD

**Issue by AnaMariaSalai1** [plivo/plivo-python#128]
Hi,

I've been trying to work with Pivlo and a Raspberry Pi 4 B model. Using the code below, I was able to receive a phone call. However, the call dropped immediately and i couldn't hear the message. Bulks calls are also not working. 

It would be really appreciated if you'd update the documentation on the website - there's a lot of confusing regarding RestAPI and RestClient.

`import plivo

client = plivo.RestClient(auth_id='XXX',auth_token='XXX')

call_made = client.calls.create(
    from_='XXX',
    to_='XXX',
    answer_url='https://s3.amazonaws.com/static.plivo.com/answer.xml'
    )`

**Comment by nixonsam** [comment]
@AnaMariaSalai1 Are you still facing any issues?

Meanwhile, feel free to contact our [support team](https://support.plivo.com/support/home) at any time.

**Comment by huzaif-plivo** [comment]
Here for call disconnection, the issue is due to the absence of answer_method. The below code snippet should help you overcome the disconnection

```
import plivo
from plivo import exceptions

client = plivo.RestClient ("auth_id", "auth_token")
try:
    response = client.calls.create(
        from_='14152225555',
        to_='+14152223333',
        answer_url='http://s3.amazonaws.com/static.plivo.com/answer.xml',
        answer_method='GET', )
    print(response)
except exceptions.ValidationError as e:
    print(e)
```

Regarding bulk calls, it may be with respect to account configuration for which feel free to contact our [support team](https://support.plivo.com/hc/en-us) at any time.
