### ISSUE TITLE
Send call xml as payload instead of providing url 

### ISSUE THREAD

**Issue by MaxNoe** [plivo/plivo-python#18]
It would be a lot easier for us, if we could just provide the xml via the post request for calls instead of providing a url from which plivo requests the xml.

**Comment by cachrisman** [comment]
Can you give an example of how you would use this?

**Comment by MaxNoe** [comment]
I would like somthing like this:

```{python}
import plivo

plivo_api = plivo.RestAPI(myid, mytoken)

xml = '''<?xml version="1.0" encoding="UTF-8" ?>
<Response>
    <Speak>Hello World</Speak>
</Response>
'''

plivo_api.Call.send(
    src=my_number,
    to=number_to_call,
    xml=xml,
)
```

**Comment by cachrisman** [comment]
Unfortunately, that isn't how the Plivo platform operates. There are a couple of reasons the system is designed like it is:
- by supplying an answer_url that returns the XML, Plivo can report the call status events (e.g., when the call is ringing, answered, hung up, etc.) to your system and you can then make changes to the call flow based on those events.
- you can specify multiple `to` numbers all with one answer_url and based on the number called, the answer url can respond with different xml

**Comment by MaxNoe** [comment]
I do not want to remove the ability to provide an `answer_url`.

But for a lot of simpler use cases than the ones you mentioned (callling, say a message, hangup) it would be a lot simpler to just send the xml instead of having a webserver delivering it.

**Comment by gurteshwar** [comment]
+1

maybe it makes sense for simple use cases like reading out an OTP using speak/play?
also it would be a lot of less dev work for people to move to Plivo if this is all they need from the service.

**Comment by cachrisman** [comment]
A simple option is to use something like [URL Echo](http://ivanzuzak.info/urlecho/) for your answer url and urlencode your xml.

```python
import plivo, plivoxml
import urllib

auth_id = "XXXXXXXXXXXXXXXXXXXX"
auth_token = "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
p = plivo.RestAPI(auth_id, auth_token)
r = plivoxml.Response()

body = u'Congratulations! You have successfully made a call with Pleevo.'
params = {
    'language': "en-US",
    'voice': "MAN"
}
r.addSpeak(body, **params)

answer_url = r'http://urlecho.appspot.com/echo?status=200&Content-Type=text%2Fxml&body=' + urllib.quote_plus(r.to_xml())

params = {
    'to': '12125551234',
    'from' : '14155556789',
    'answer_url' : answer_url,
    'answer_method' : "GET"
}

response = p.make_call(params)
print str(response)

**Comment by MaxNoe** [comment]
I just found `twimlets.com` from coming from twilio. They have some standard xml files for voice.

To send someone a Hello, World voice message, do this:

```{python}
from requests import Request
import plivo

r = Request('GET', ''http://twimlets.com/message', params={'Message': 'Hello, World!''} )
url = r.prepare().url

plivo_api = plivo.RestAPI(myid, mytoken)

plivo_api.Call.send(
    src=my_number,
    to=number_to_call,
    url=url,
)
```

**Comment by cachrisman** [comment]
I've also made [Plivlets](https://plivlets.herokuapp.com/)

**Comment by gurteshwar** [comment]
While Plivlets definitely looks useful, I guess it can only serve static XML?
My use case is to generate a dynamic OTP for every call and use it with Speak XML

**Comment by gurteshwar** [comment]
ok, @cachrisman didn't read through your comment properly. URL Echo solves my problem.

Thanks

**Comment by mataneine** [comment]
> I've also made Plivlets
Should be mentioned in Plivo documentation
