### ISSUE TITLE
More flexible dependency version needed for PyJWT

### ISSUE THREAD

**Issue by zmsp** [plivo/plivo-python#182]
This python library has a strict dependency on a very old [`PyJWT==1.7.1`](https://github.com/plivo/plivo-python/blob/63e2c8f7d1c605e57f1ce9dcf50b763edf626340/setup.py#L42) library. Modern Pip causes dependency error when installing plivo. To support newer versions of python, this needs to be resolved.

**Comment by narayana-plivo** [comment]
@zmsp Here is the PR for the fix. https://github.com/plivo/plivo-python/pull/184

@huzaif-plivo Please merge it

**Comment by joshlsullivan** [comment]
Same issue here. This works for me:
PyJWT = "==2.1.0"
plivo = "==4.18.0"

**Comment by huzaif-plivo** [comment]
@joshlsullivan @zmsp Thank you for the feedback, we have fixed and released this in our latest [version](https://github.com/plivo/plivo-python/releases/tag/4.19.1).
