### ISSUE TITLE
Mismatch between setup.py and requirements.txt for pyjwt lib

### ISSUE THREAD

**Issue by uhurusurfa** [plivo/plivo-python#183]
The setup.py file specifies: 'PyJWT==1.7.1'
The requirements.txt specifies: PyJWT==2.1.0

This is creating problems with other libraries that have moved to pyjwt 2.0 and no longer support earlier versions.
Was this intentional and is there an expected time when pyjwt >= 2.0 will be supported?

**Comment by allanhart** [comment]
I encountered this issue as well. I saw no alternative but to fork the project, update setup.py with the correct version (2.1.0), then build the package myself. I very much hope that this minute but _critical_ issue can be resolved in a timely manner.

**Comment by narayana-plivo** [comment]
@uhurusurfa @allanhart here is the fix https://github.com/plivo/plivo-python/pull/184.

@huzaif-plivo Please merge to master

**Comment by joshlsullivan** [comment]
Same issue here. This works for me:
PyJWT = "==2.1.0"
plivo = "==4.18.0"

**Comment by huzaif-plivo** [comment]
@allanhart @uhurusurfa @joshlsullivan Thank you for the feedback, we have fixed and released this in our latest release[version](https://github.com/plivo/plivo-python/releases/tag/4.19.1).
