### ISSUE TITLE
digitsMatchBLeg parameter doesnt work for addDial | invalid attribute digitsMatchBLeg for Dial

### ISSUE THREAD

**Issue by minhajresgef** [plivo/plivo-python#33]
when tried to use digitsMatchBLeg parameter for addDial method, it shows error:

**invalid attribute digitsMatchBLeg for Dial**

> PlivoError at /plivotest/ivr-answer/
> invalid attribute digitsMatchBLeg for Dial
> Request Method:	POST
> Request URL:	http://subdomain.ngrok.io/plivotest/ivr-answer/
> Django Version:	1.9.5
> Exception Type:	PlivoError
> Exception Value: invalid attribute digitsMatchBLeg for Dial
> Exception Location:	myvirtualenv/local/lib/python2.7/site-packages/plivoxml.py in __init__, line 18
> Python Executable:	myvirtualenv/bin/python2
> Python Version:	2.7.13

to use this parameter, I had to construct the Dial response xml on myself

**Comment by plivo-sdks** [comment]
Fixed in 3dab8c520fc13691aa0346c1b93ba2cf44788042
