### ISSUE TITLE
I'm having an issue installing Plivo

### ISSUE THREAD

**Issue by tomforsyth90** [plivo/plivo-python#42]
i'm having a problem installing it and i'm getting this error:

*********************************************************************************
Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
*********************************************************************************
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GVzrek/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-S_g0er-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-GVzrek/lxml/

Hope you can help

**Comment by plivo-sdks** [comment]
@tomforsyth90 Seems like libxml2 of the necessary development libraries by lxml aren't installed.

Try installing `libxml2-dev` and `libxslt1-dev`. Depending on your system, use `sudo apt-get install` or `brew install` to install these.

**Comment by tomforsyth90** [comment]
@plivo-sdks thanks that seems to have installed properly now
