### ISSUE TITLE
Not sure what i'm doing wrong

### ISSUE THREAD

**Issue by tomforsyth90** [plivo/plivo-python#43]
Hi thanks for sorting out the installation problem I had, I've managed to get it installed properly now.
I've made an account on the dashboard and I have an auth ID and auth token. I created a file called make_calls.py which has the following in:
from plivo import plivoxml

auth_id = "*********************"
auth_token = "*************************"

p = plivo.RestAPI(auth_id, auth_token)

params = {
  'to': '+44********',   
  'from' : '1111111111', 
  'answer_url' : "https://s3.amazonaws.com/static.plivo.com/answer.xml",
  'answer_method' : "GET",
}

response = p.make_call(params)
print str(response) 

*************************************************
But i'm not sure what I need to do to get this to work? Do you mind explaining step by step and how to do it as I've never really done anything like this before and am struggling to understand what I'm required to do to get Plivo to work properly   :(.

Thanks

**Comment by plivo-sdks** [comment]
@tomforsyth90 Ah! Seems like you are using the old version of docs.

Check out https://developers.plivo.com/getting-started/calls/. It even has detailed sample code in Python. 

Similarly, visit https://developers.plivo.com/getting-started/messages/ to see how to send an SMS.
