### ISSUE TITLE
How to get call_uuid from a call placed

### ISSUE THREAD

**Issue by krishthotem** [plivo/plivo-python#44]
Hi, 

I have the following code and it works fine. 

`client = plivo.RestClient('**', '**')`
`call_made = client.calls.create(
                from_ = '**', 
                to_ =   '**', 
                answer_url = 'http://s3.amazonaws.com/static.plivo.com/answer.xml',
                answer_method = 'GET',)`

I checked this link (https://www.plivo.com/docs/getting-started/get-details-of-a-single-call/) and other links. However I was unable to understand how on line 9 ('call_uuid': '55309cee-821d-11e4-9a73-498d468c930b) the author was able to get the value for call_uuid ?? How in the first place should one be able to get that value?

**Comment by plivo-sdks** [comment]
@krishthotem  You are referring to the documentation of the older SDK.

You will be access the call_uuid by `call_made.request_uuid`. The request_uuid is the call_uuid.
