### ISSUE TITLE
TypeError when listing all endpoints

### ISSUE THREAD

**Issue by kicdu** [plivo/plivo-python#48]
Server SDK should handle pagination automatically. 
Code snippet:
```
with plivo.RestClient(auth_id = auth_id, auth_token = auth_token) as client:
    for e in client.endpoints:
        print e['_name']
```
Result is traceback:

```
TypeError                                 
Traceback (most recent call last)
<ipython-input-5-7acc734a5550> in <module>()
      1 with plivo.RestClient(auth_id = auth_id, auth_token = auth_token) as client:
----> 2     for e in client.endpoints:
      3         print e['_name']

~/venv/local/lib/python2.7/site-packages/plivo/base.pyc in gen()
    216             offset = 0
    217             while True:
--> 218                 response = self.list(limit=limit, offset=offset)
    219                 if not response.objects:
    220                     return

TypeError: list() got an unexpected keyword argument 'limit'

```

**Comment by nixonsam** [comment]
@kicdu Its working as expected. check screenshots. 

![image](https://user-images.githubusercontent.com/37671608/52933602-e8b8df00-3379-11e9-9dac-6cd4bdc70e94.png)
![image](https://user-images.githubusercontent.com/37671608/52933609-ee162980-3379-11e9-8782-30f7e210eee6.png)

Feel free to create a support ticket if you need any assistance or in case of any concerns.

**Comment by kicdu** [comment]
Yes, it's working right now after you changed it in https://github.com/plivo/plivo-python/commit/e648435ff70cdb698dec8b5a22b21438ed840821 .

May 2018. I made PR #49 that fixes it, but you ignored it. :( 

Anyways thanks for update.
