### ISSUE TITLE
How about upgrading lxml to 4.x?

### ISSUE THREAD

**Issue by netcaf** [plivo/plivo-python#56]
Plivo is always complaining about lxml 4.x which is incompatible?

**Comment by hust-whw** [comment]
If you use pip3 of python3.7, that will crash your installation of lxml 3.x.
But the latest plivo-python required lxml>3 and <4.

What you need to do is to install the pre-version 4.2.0a3
`pip3 install plivo==4.2.0a3`
which is compatible with python3.7 and has lxml 4.x as dependency.

**Comment by nixonsam** [comment]
We are already using **lxml** v4. PFA screenshot

![image](https://user-images.githubusercontent.com/37671608/52933817-890f0380-337a-11e9-9382-89caece5b0aa.png)
