### ISSUE TITLE
Plivo is not supporting pip3

### ISSUE THREAD

**Issue by varunajmera0** [plivo/plivo-python#65]
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/fc/lcypm16j63gddb7mq3s15x_00000gn/T/pip-install-ygunk1h4/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/fc/lcypm16j63gddb7mq3s15x_00000gn/T/pip-record-04fedc8b/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/fc/lcypm16j63gddb7mq3s15x_00000gn/T/pip-install-ygunk1h4/lxml/

![screen shot 2018-08-23 at 5 40 10 pm](https://user-images.githubusercontent.com/22893376/44524608-d710ba80-a6fb-11e8-87d2-8d1c359daf06.png)

**Comment by hust-whw** [comment]
Same issue as #56 

> If you use pip3 of python3.7, that will crash your installation of lxml 3.x.
But the latest plivo-python required lxml>3 and <4.
> What you need to do is to install the pre-version 4.2.0a3
> `pip3 install plivo==4.2.0a3`
> which is compatible with python3.7 and has lxml 4.x as dependency.

unless you downgrade your python version lol

**Comment by nixonsam** [comment]
closing this.
