### ISSUE TITLE
AttributeError: module 'plivo' has no attribute 'RestAPI' + module 'plivo' has no attribute 'Client'

### ISSUE THREAD

**Issue by enuvoola** [plivo/plivo-python#74]
I am trying to use Plivo for an URGENT prototype  and I am getting the following error messages related to Plivo libraries

(1) AttributeError: module 'plivo' has no attribute 'RestAPI'
(2) AttributeError: module 'plivo' has no attribute 'Client'

HERE IS HOW I GET ERROR (1) 

at python3 console

 import plivo

auth_id = 'xxxx'
auth_token = 'xxxxx'
p = plivo.RestAPI(auth_id, auth_token)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'plivo' has no attribute 'RestAPI'

HERE IS HOW I GET ERROR (2) 

def usePlivo(msg, dst):
    client = plivo.Client('xxxxx', 'xxxx')
    try:
        response = client.messages.create(
            src= '16132222222',
            dst= dst,
            text= msg,
        )
        print(response.__dict__)
    except plivo.exceptions.PlivoRestError as e:
        print(e)
    return;

>>> usePlivo(msg, dst)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in usePlivo
AttributeError: module 'plivo' has no attribute 'Client'

ADDITIONAL INFO

Running python3 in a venv 

 dir (plivo)
['RestClient', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'base', 'exceptions', 'plivoxml', 'resources', 'rest', 'utils', 'version', 'xml']

 print (plivo.__file__)
/home/clout/repo/emily/env/lib/python3.5/site-packages/plivo/__init__.py

contents of version.py
__version__ = '4.1.3'

 contents of version __init.py__
from . import exceptions
from .rest import Client as RestClient
from . import xml as plivoxml

(env) clout@tubu:~/repo/emily$ pip install plivo
Requirement already satisfied: plivo in ./env/lib/python3.5/site-packages (4.1.3)
Requirement already satisfied: decorator<5,>=4 in ./env/lib/python3.5/site-packages (from plivo) (4.3.0)
Requirement already satisfied: six<2,>=1 in ./env/lib/python3.5/site-packages (from plivo) (1.11.0)
Requirement already satisfied: lxml<5,>=3 in ./env/lib/python3.5/site-packages (from plivo) (4.2.5)
Requirement already satisfied: requests<3,>=2 in ./env/lib/python3.5/site-packages (from plivo) (2.19.1)
Requirement already satisfied: idna<2.8,>=2.5 in ./env/lib/python3.5/site-packages (from requests<3,>=2->plivo) (2.7)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in ./env/lib/python3.5/site-packages (from requests<3,>=2->plivo) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python3.5/site-packages (from requests<3,>=2->plivo) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.5/site-packages (from requests<3,>=2->plivo) (2018.8.24)

Your help will be appreciated!

Thank you

**Comment by rjsu26** [comment]
I am having the same problem, even after exactly following the instructions

**Comment by JPMarin92** [comment]
Any solutuon to this problem ? The same thing is happening to me

**Comment by nixonsam** [comment]
@enuvoola  @rjsu26 @JPMarin92 

It is working as expected

#Python3.7

import plivo
client = plivo.RestClient()

dir(plivo)                                                                                                                                     
['RestClient',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'base',
 'exceptions',
 'plivoxml',
 'resources',
 'rest',
 'utils',
 'version',
 'xml']

Looks like you're accessing an incorrect `Class`

p = plivo.RestAPI(auth_id, auth_token)
Traceback (most recent call last):
File "", line 1, in 
AttributeError: module 'plivo' has no attribute 'RestAPI'

dir (plivo)
['RestClient', '**builtins**', '**cached**', '**doc**', '**file**', '**loader**', '**name**', '**package**', '**path**', '**spec**', 'base', 'exceptions', 'plivoxml', 'resources', 'rest', 'utils', 'version', 'xml']

We don’t have any Class named RestAPI we have RestClient.

Feel free to contact support if you need any further assistance or in case of any concerns. 
Thank you.

**Comment by LMillsSplunk** [comment]
You example on this Getting Started tutorial uses RestAPI: https://www.plivo.com/docs/voice/getting-started/basic/making-outbound-calls/ which I assume is incorrect. Could you please update this guide.

**Comment by nixonsam** [comment]
sure, we will update the same. Thank you!
