### ISSUE TITLE
Call recording on On-going call

### ISSUE THREAD

**Issue by DhruvMevada** [plivo/plivo-python#88]
Can it possible to record the call streaming while call is on going in Plivo?

**Comment by nixonsam** [comment]
@DhruvMevada yes, you can use https://api-reference.plivo.com/latest/python/resources/call/record-calls/start-recording-a-call to record an ongoing call.

**Comment by DhruvMevada** [comment]
Ya but But how can I get the recorded audio meanwhile the call is on going?

**Comment by scheung38** [comment]
any update on this?

**Comment by nixonsam** [comment]
@DhruvMevada @scheung38 Plivo will post the recording details such as recording URL, call_uuid, recording_duration, etc,  to the callback_url of [Record a Call API](https://www.plivo.com/docs/voice/api/call/record-calls#start-recording-a-call) and callbackUrl of [Record XML](https://www.plivo.com/docs/voice/xml/record/). You can access the recording file from the recording URL once the recording is completed. However, you can not get the live audio stream in the recording URL. Thanks!
